# fly.toml app configuration file generated for elhadj-abdoul-diallo-quote-generator-still-darkness-1788 on 2025-03-13T22:19:13Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'elhadj-abdoul-diallo-quote-generator-still-darkness-1788'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
